[package]
name = "lox-interpreter-rust"
version = "0.1.0"
authors = ["Adlizm <adlizm.pq@gmail.com>"]
edition = "2021"
rust-version = "1.80"

[dependencies]
clap = { version = "4.5.40", features = ["derive"] }
thiserror = "1.0.38"                                 # error handling
